### ISSUE TITLE
FR: Keyboard support

### ISSUE THREAD

**Issue by TheWizier** [lucasteles/InputDisplay#5]
I use a keyboard for playing, it seems this only supports controllers?
It would be nice to have keyboard support as well.

**Comment by lucasteles** [comment]
@TheWizier yes, I want to add keyboard support, I let you know here when it happens

**Comment by lucasteles** [comment]
Hi @TheWizier, the keyboard support just dropped in https://github.com/lucasteles/InputDisplay/releases/tag/0.5.3

**Comment by TheWizier** [comment]
Nice!
